'use client';
import {AnimatePresence,motion} from 'framer-motion';
import {useEffect,useState} from 'react';
import {connect,CONTRACT,EXPLORER,read,write} from '../lib/chain';

const packets=[
 {id:'PKT-9A71',route:'SRE → PAYMENTS',title:'Key rotation handoff',risk:'MED',status:'VALIDATING',age:'04:18',progress:64},
 {id:'PKT-4D20',route:'AGENT-7 → OPS',title:'Queue recovery context',risk:'LOW',status:'READY',age:'11:03',progress:100},
 {id:'PKT-1F88',route:'DEPLOY → SECURITY',title:'Privilege boundary change',risk:'HIGH',status:'REROUTE',age:'18:44',progress:42},
];
const nodes=[{name:'ORIGIN',sub:'SRE-ALPHA'},{name:'INGRESS',sub:'CHECKSUM'},{name:'JUNCTION',sub:'5 VALIDATORS'},{name:'DESTINATION',sub:'PAYMENTS'}];

function Mark(){return <svg viewBox="0 0 42 42"><path d="M5 8h11v11H5zM26 23h11v11H26zM16 13h10M21 13v15M21 28h5"/><circle cx="21" cy="28" r="3"/></svg>}
function Wave({phase=0}:{phase?:number}){return <svg className="wave" viewBox="0 0 500 90" preserveAspectRatio="none"><path d={`M0 48 L35 48 L46 ${25+phase} L58 68 L72 31 L85 48 L130 48 L143 18 L158 75 L174 40 L188 48 L245 48 L260 28 L276 65 L290 48 L345 48 L359 20 L375 72 L390 35 L407 48 L500 48`}/><line x1="0" y1="48" x2="500" y2="48"/></svg>}
function Skeleton(){return <div className="skeleton"><div className="sk-head"/><div className="sk-line"><i/><i/><i/><i/><b/></div><div className="sk-wave"/><div className="sk-scan"/></div>}

export default function Home(){
 const[loading,setLoading]=useState(true),[selected,setSelected]=useState(0),[inspect,setInspect]=useState(false),[live,setLive]=useState(true),[wallet,setWallet]=useState(''),[phase,setPhase]=useState(''),[hash,setHash]=useState(''),[error,setError]=useState(''),[summary,setSummary]=useState<any>({protocols:0,packets:0,decisions:0}),[decision,setDecision]=useState<any>(),[pendingPacket,setPendingPacket]=useState(''),[chainPackets,setChainPackets]=useState<any[]>([]);
 const pendingKey=`relay.pendingPacket:${CONTRACT}`;
 const refresh=async()=>{try{const s:any=await read('get_summary');setSummary(s);try{const page:any=await read('get_packets_page',[0,50]);setChainPackets([...(page.items||[])].reverse())}catch{}}catch{}};useEffect(()=>{const t=setTimeout(()=>setLoading(false),1100);setPendingPacket(localStorage.getItem(pendingKey)||'');refresh();return()=>clearTimeout(t)},[]);
 const progress=(p:string,h?:string)=>{setPhase(p);if(h)setHash(h)};
 const busy=['WALLET APPROVAL','AI CONSENSUS','RECONNECTING TO BRADBURY'].includes(phase);
 const seal=async()=>{try{setError('');const liveSummary:any=await read('get_summary');if(!liveSummary.protocols)throw Error('Protocol setup is required once before sealing packets.');let packetId=pendingPacket;if(!packetId){packetId=`PKT-${crypto.randomUUID().slice(0,8).toUpperCase()}`;setPendingPacket(packetId);localStorage.setItem(pendingKey,packetId)}let exists=true;try{await read('get_packet',[packetId])}catch{exists=false}if(!exists)await write('submit_packet',[packetId,'ops-handoff-v1','PAYMENTS','Transfer responsibility for the active key-rotation window without interrupting settlement services.',['Replay workers retain the prior credential for twelve minutes.'],['worker pool','KMS alias'],'Revert the KMS alias, drain workers, verify signature epoch, then reopen ingress.',['runbook attached','rotation telemetry attached']],progress);setPhase('PACKET SEALED — READY FOR INSPECTION');setInspect(false);await refresh()}catch(e:any){setError(String(e?.message||e));setPhase('FAILED')}};
 const inspectPending=async()=>{if(!pendingPacket)return;try{setError('');await write('inspect_handoff',[pendingPacket],progress);setDecision(await read('get_decision',[pendingPacket]));localStorage.removeItem(pendingKey);setPendingPacket('');setPhase('DECISION WRITTEN');await refresh()}catch(e:any){setError(String(e?.message||e));setPhase('FAILED')}};
 if(loading)return <main><Skeleton/></main>;
 const onchain=chainPackets.map((p:any)=>({id:p.id,route:`${String(p.sender).slice(0,6)} → ${p.recipient}`,title:p.objective,risk:'LIVE',status:p.gate||String(p.status).toUpperCase(),age:'ON-CHAIN',progress:p.status==='settled'?100:68}));const shownPackets=onchain.length?onchain:packets;const packet=shownPackets[selected]||shownPackets[0];
 return <main className="app"><div className="grid"/><header><div className="brand"><Mark/><div><b>RELAY / DISCIPLINE</b><small>SEMANTIC HANDOFF NETWORK</small></div></div><div className="network"><i/> GENLAYER STUDIONET <span>{summary.packets} ON-CHAIN PACKETS</span></div><button className="wallet" disabled={busy} onClick={async()=>{try{setWallet(await connect())}catch(e:any){setError(String(e?.message||e))}}}>{wallet?`${wallet.slice(0,6)} · ${wallet.slice(-4)}`:'CONNECT WALLET'}</button></header>
 <div className="statusbar"><span>NETWORK <b>RD-PRIMARY</b></span><span>PROTOCOL <b>OPS-HANDOFF / V3.4</b></span><span>JUNCTION HEALTH <b>05 / 05</b></span><button onClick={()=>setLive(!live)}><i className={live?'on':''}/> {live?'LIVE FLOW':'FLOW PAUSED'}</button></div>
 <section className="topology">
  <div className="top-title"><div><small>ACTIVE TRANSFER</small><h1>{packet.title}</h1></div><div className="packet-code"><span>{packet.id}</span><b>{packet.status}</b></div></div>
  <div className="rail">
   <div className="energy" style={{width:`${packet.progress}%`}}/>
   {nodes.map((n,i)=><motion.div className={`station ${i<=Math.floor(packet.progress/27)?'lit':''}`} key={n.name} initial={{scale:.7,opacity:0}} animate={{scale:1,opacity:1}} transition={{delay:i*.15}}><div className="node"><span>{String(i+1).padStart(2,'0')}</span><i/></div><b>{n.name}</b><small>{n.sub}</small></motion.div>)}
   {live&&<motion.div className="traveller" key={selected} initial={{left:'3%'}} animate={{left:`${Math.min(packet.progress,94)}%`}} transition={{duration:1.5,ease:'easeInOut'}}><span>{packet.id}</span></motion.div>}
  </div>
  <div className="route-meta"><span>SOURCE SIGNATURE <b>VERIFIED</b></span><span>PAYLOAD <b>18.4 KB</b></span><span>TTL <b>00:42:18</b></span><span>DEPENDENCIES <b>03 BOUNDED</b></span></div>
 </section>
 <div className="lower">
  <aside className="queue"><div className="section-label"><span>01</span> TRANSFER QUEUE <b>{shownPackets.length}</b></div>{shownPackets.map((p,i)=><button key={p.id} onClick={()=>setSelected(i)} className={selected===i?'active':''}><div><b>{p.id}</b><span className={`risk ${p.risk}`}>{p.risk}</span></div><h3>{p.title}</h3><small>{p.route}</small><footer><span>{p.status}</span><span>{p.age}</span></footer></button>)}</aside>
  <section className="scope"><div className="section-label"><span>02</span> PROTOCOL OSCILLOSCOPE <b>LIVE SAMPLE / 240 HZ</b></div><div className="scope-screen"><div className="scope-grid"/><Wave phase={selected*4}/><div className="cursor"/><div className="scope-labels"><span>HANDOFF SUFFICIENCY <b>82.6</b></span><span>RISK DISCLOSURE <b>71.4</b></span><span>RECOVERY CONTEXT <b>94.1</b></span></div></div><div className="obligations"><div><i className="ok"/><span>OWNER &amp; INTENT</span><b>RESOLVED</b></div><div><i className="ok"/><span>RECOVERY PATH</span><b>RESOLVED</b></div><div><i/><span>HIDDEN DEPENDENCY</span><b>REVIEW</b></div></div></section>
  <aside className="decision"><div className="section-label"><span>03</span> JUNCTION DECISION</div><div className="dial"><div><b>{decision?5:4}</b><small>/ 5 ALIGNED</small></div><i/><i/><i/></div><h2>{pendingPacket?'PACKET AWAITS INSPECTION':(decision?.gate||'READY_WITH_ACK').replaceAll('_',' ')} </h2><p>{pendingPacket?'The packet is already on-chain. Start validator inspection when you are ready.':decision?.reason||'Destination must acknowledge the payment replay dependency before accepting custody.'}</p><button disabled={busy} onClick={pendingPacket?inspectPending:()=>setInspect(true)}>{pendingPacket?'REQUEST VALIDATOR INSPECTION':'BUILD HANDOFF'} <span>↗</span></button><small>{summary.decisions} VERIFIED ON-CHAIN DECISIONS</small></aside>
 </div>
 <AnimatePresence>{inspect&&<motion.div className="overlay" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setInspect(false)}><motion.div className="drawer" initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}} transition={{type:'spring',damping:28}} onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setInspect(false)}>CLOSE ×</button><small>NEW ON-CHAIN HANDOFF</small><h2>Custody transfer manifest</h2><div className="manifest"><span>01 / OBJECTIVE</span><p>Transfer responsibility for the active key-rotation window without interrupting settlement services.</p><span>02 / KNOWN RISK</span><p>Replay workers retain the prior credential for up to twelve minutes after rotation.</p><span>03 / RECOVERY</span><p>Revert KMS alias, drain worker pool, verify signature epoch, then reopen ingress.</p></div><button className="seal" disabled={!wallet||busy} onClick={seal}>{phase||'SEAL PACKET ON-CHAIN'}</button></motion.div></motion.div>}</AnimatePresence>
 {(phase||error)&&<div className={`chain-progress ${error?'failed':''}`}><b>{error?'TRANSFER NEEDS ATTENTION':phase}</b><span>{error||'Keep this page open while the packet crosses the validator junction.'}</span>{hash&&<a href={`${EXPLORER}/${hash}`} target="_blank">VIEW TRANSACTION ↗</a>}<button onClick={()=>{setPhase('');setError('')}}>×</button></div>}
 </main>
}
