'use client';
import {createAccount,createClient} from 'genlayer-js';
import {testnetBradbury} from 'genlayer-js/chains';
export const CONTRACT='0x1EACD7324A6BFAE87851e740706BB5f48EC4705F' as `0x${string}`;
export const EXPLORER='https://explorer-bradbury.genlayer.com/transactions';
const endpoint='https://rpc-bradbury.genlayer.com';
const reader:any=createClient({chain:testnetBradbury,endpoint,account:createAccount()});let wallet:any;let connectPromise:Promise<string>|null=null;
const pause=(n:number)=>new Promise(r=>setTimeout(r,n));
const transient=(e:any)=>/pipeline backpressure|not currently accepting|l1_sender_commit|failed to fetch|networkerror|network request failed|timeout/i.test(String(e?.message||e));
async function waitForAccount(eth:any){for(let i=0;i<120;i++){const accounts=await eth.request({method:'eth_accounts'}).catch(()=>[]);if(accounts?.[0])return accounts[0] as string;await pause(500)}throw Error('Wallet selection timed out. Close the wallet picker and try again.')}
export async function connect(){if(connectPromise)return connectPromise;connectPromise=(async()=>{const eth=(window as any).ethereum;if(!eth)throw Error('Install Rabby or MetaMask first.');let accounts:any[]=[];try{accounts=await eth.request({method:'eth_requestAccounts'})}catch(e:any){if(!/already processing connect/i.test(String(e?.message||e)))throw e;accounts=[await waitForAccount(eth)]}const a=accounts?.[0];if(!a)throw Error('No wallet selected.');const id='0x107d';if(String(await eth.request({method:'eth_chainId'})).toLowerCase()!==id){try{await eth.request({method:'wallet_switchEthereumChain',params:[{chainId:id}]})}catch(e:any){if(e?.code!==4902)throw Error('Approve the Bradbury network switch.');await eth.request({method:'wallet_addEthereumChain',params:[{chainId:id,chainName:'GenLayer Bradbury Testnet',nativeCurrency:{name:'GEN',symbol:'GEN',decimals:18},rpcUrls:[endpoint],blockExplorerUrls:['https://explorer-bradbury.genlayer.com']}]});await eth.request({method:'wallet_switchEthereumChain',params:[{chainId:id}]})}}wallet=createClient({chain:testnetBradbury,endpoint,account:a,provider:eth});await wallet.initializeConsensusSmartContract?.().catch(()=>{});return a as string})();try{return await connectPromise}finally{connectPromise=null}}
export async function read<T>(name:string,args:any[]=[]){let last:any;for(let i=0;i<4;i++){try{return await reader.readContract({address:CONTRACT,functionName:name,args}) as T}catch(e){last=e;if(!transient(e))throw e;await pause(1800*(i+1))}}throw last}
export async function write(name:string,args:any[],progress:(p:string,h?:string)=>void){if(!wallet)throw Error('Connect your wallet first.');progress('WALLET APPROVAL');const hash:string=await wallet.writeContract({address:CONTRACT,functionName:name,args,value:0n});progress('AI CONSENSUS',hash);let receipt:any,last:any;for(let i=0;i<2;i++){try{receipt=await wallet.waitForTransactionReceipt({hash,status:'ACCEPTED',retries:30,interval:30000});break}catch(e){last=e;if(!transient(e))throw e;progress('RECONNECTING TO BRADBURY',hash);await pause(5000)}}if(!receipt)throw last||Error('Could not confirm the transaction receipt.');let tx:any;for(let i=0;i<4;i++){try{tx=await wallet.getTransaction({hash});break}catch(e){if(!transient(e))throw e;await pause(3000*(i+1))}}const result=tx?.consensus_data?.leader_receipt?.[0]?.execution_result??receipt?.tx_execution_result??receipt?.txExecutionResult;if(String(result)==='2')throw Error('Consensus accepted the transaction, but contract execution rolled back.');progress('ON-CHAIN',hash);return hash}
